//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.TempShiftService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DayOfWeek", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public enum DayOfWeek : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sunday = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monday = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tuesday = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wednesday = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thursday = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friday = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Saturday = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TempShiftService.ITempShiftService")]
    public interface ITempShiftService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITempShiftService/CreateTempShift", ReplyAction="http://tempuri.org/ITempShiftService/CreateTempShiftResponse")]
        Core.TemplateShift CreateTempShift(Tests.TempShiftService.DayOfWeek weekDay, double hours, System.TimeSpan startTime, int templateScheduleID, Core.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITempShiftService/CreateTempShift", ReplyAction="http://tempuri.org/ITempShiftService/CreateTempShiftResponse")]
        System.Threading.Tasks.Task<Core.TemplateShift> CreateTempShiftAsync(Tests.TempShiftService.DayOfWeek weekDay, double hours, System.TimeSpan startTime, int templateScheduleID, Core.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITempShiftService/FindTempShiftByID", ReplyAction="http://tempuri.org/ITempShiftService/FindTempShiftByIDResponse")]
        Core.TemplateShift FindTempShiftByID(int tempShiftID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITempShiftService/FindTempShiftByID", ReplyAction="http://tempuri.org/ITempShiftService/FindTempShiftByIDResponse")]
        System.Threading.Tasks.Task<Core.TemplateShift> FindTempShiftByIDAsync(int tempShiftID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITempShiftServiceChannel : Tests.TempShiftService.ITempShiftService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TempShiftServiceClient : System.ServiceModel.ClientBase<Tests.TempShiftService.ITempShiftService>, Tests.TempShiftService.ITempShiftService {
        
        public TempShiftServiceClient() {
        }
        
        public TempShiftServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TempShiftServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempShiftServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempShiftServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Core.TemplateShift CreateTempShift(Tests.TempShiftService.DayOfWeek weekDay, double hours, System.TimeSpan startTime, int templateScheduleID, Core.Employee employee) {
            return base.Channel.CreateTempShift(weekDay, hours, startTime, templateScheduleID, employee);
        }
        
        public System.Threading.Tasks.Task<Core.TemplateShift> CreateTempShiftAsync(Tests.TempShiftService.DayOfWeek weekDay, double hours, System.TimeSpan startTime, int templateScheduleID, Core.Employee employee) {
            return base.Channel.CreateTempShiftAsync(weekDay, hours, startTime, templateScheduleID, employee);
        }
        
        public Core.TemplateShift FindTempShiftByID(int tempShiftID) {
            return base.Channel.FindTempShiftByID(tempShiftID);
        }
        
        public System.Threading.Tasks.Task<Core.TemplateShift> FindTempShiftByIDAsync(int tempShiftID) {
            return base.Channel.FindTempShiftByIDAsync(tempShiftID);
        }
    }
}
